const ItemGroupTypes = Object.freeze({
    SERVICE_STATE_GROUP             : Symbol("SERVICE_STATE_GROUP"),
    INSTANCE_STATE_GROUP            : Symbol("INSTANCE_STATE_GROUP"),
    STORAGE_STATE_GROUP             : Symbol("STORAGE_STATE_GROUP"),
    STORAGE_PARAM_STATE_GROUP       : Symbol("STORAGE_PARAM_STATE_GROUP"),
    SOCKET_STATE_GROUP              : Symbol("SOCKET_STATE_GROUP"),
    SOCKET_PARAM_STATE_GROUP        : Symbol("SOCKET_PARAM_STATE_GROUP"),
    CONTAINER_STATE_GROUP           : Symbol("CONTAINER_STATE_GROUP"),
    IMAGE_BUILD_HISTORY_STATE_GROUP : Symbol("IMAGE_BUILD_HISTORY_STATE_GROUP")
})

module.exports = ItemGroupTypes